#!/usr/bin/python
"""

    Controls a relay based on the comparision of an id in the database
    Useful for rfid-controled doors
    To think this was a shell script a few days ago...

    Copyright (C) 2013 TheOtherNet LLC
    Copyright (C) 2013 David Francos Cuartero <dfrancos@theothernet.co.uk>

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
    02110-1301, USA.

"""
import RPi.GPIO as GPIO
import time
import MySQLdb

class DoorOpener(object):
    """
        Main dooropener class
    """
    def __init__(self):
        """
            Set up the gpio, launch the main bucle
        """
        self.log_ = open('/tmp/simpledod.log', 'w')
        self.database = MySQLdb.connect(
            "localhost",
            "root",
            "root",
            "lcdv"
        )
        self.pinout = 24
        GPIO.setmode(GPIO.BOARD)
        GPIO.setup(self.pinout, GPIO.OUT)

    def open_door(self):
        """
            Puts the pin in high mode for 0.1 seconds
            Enough to activate the doorlock
        """
        try:
            GPIO.output(self.pinout, GPIO.HIGH)
            time.sleep(0.1)
            GPIO.output(self.pinout, GPIO.LOW)
            time.sleep(0.3)
        except Exception, e:
            self.log(e)

    def check_access(self, id_tarjeta):
        """
            Checks that the user has acess
        """
        try:
            fecha = time.strftime("%Y-%m-%d", time.gmtime())
            cursor = self.database.cursor()
            query = 'Select * from members where id_tarjeta = \'%s\' and fechaPago >= \'%s\' and flagDisabled is null'  %(id_tarjeta, fecha)
            cursor.execute(
                query
            )
            if cursor.fetchone():
                self.log("Opening door for card %s at time %s\n" %(id_tarjeta, fecha))
                return True
            self.log("Card %s not valid, not opening at time %s with query %s\n" %(fecha, id_tarjeta, query))
            return False
        except Exception, e:
            self.log(e)

    def log(self, string):
        print(string)
        self.log_.write(string)
        self.log_.flush()

    def bucle(self):
        """
            Checks access every 0.3 seconds (waits for the raw_input,
            so not a problem)
            If access, opens door.
        """
        while True:
            try:
                if self.check_access(raw_input()):
                    self.open_door()
                    cursor = self.database.cursor()
                    cursor.execute('Insert into access_log (id_tarjeta, status) values (\'%s\', 0)' %(id_tarjeta))
            except Exception, e:
                self.log(e)

if __name__ == "__main__":
    while True:
        try:
            DoorOpener().bucle()
        except Exception, e:
            print e
            pass
